apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-chat-config
data:
  # Chat Service Configurations
  SPRING_REDIS_HOST: "{{ .Values.redis.host }}"
  SPRING_REDIS_PORT: "{{ .Values.redis.port }}"
  SPRING_REDIS_PASSWORD: "{{ .Values.redis.password }}"
  RAW_TOPIC_MESSAGE: "{{ .Values.redis.topic }}"

  # Multi-cloud support (To be updated in Task 5)
  LIST_OF_PROFILE_ENDPOINTS: "{{ .Values.chat.profileEndpoints }}"

  # MySQL Configuration for Chat Service
  MYSQL_DB_HOST: "{{ .Values.chat.mysql.host }}"  # MySQL service name in Kubernetes
  MYSQL_DB_PORT: "{{ .Values.chat.mysql.port }}"  # Default MySQL port
