{{- if eq .Values.global.environment "gcp" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.chat.releaseName }}-deployment"
  labels:
    app: spring-chat
spec:
  replicas: {{ .Values.chat.replicaCount }}
  selector:
    matchLabels:
      app: spring-chat
  template:
    metadata:
      labels:
        app: spring-chat
    spec:
      containers:
        - name: spring-chat
          image: "{{ .Values.chat.image }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: {{ .Values.chat.hpa.cpuRequest }}
          env:
            - name: MYSQL_DB_HOST
              value: "{{ .Values.chat.mysql.host }}"
            - name: MYSQL_DB_PORT
              value: "{{ .Values.chat.mysql.port }}"
            - name: MYSQL_DB_USER
              valueFrom:
                secretKeyRef:
                  name: chat-secret
                  key: mysql-username
            - name: MYSQL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chat-secret
                  key: mysql-password
            - name: SPRING_REDIS_HOST
              value: "{{ .Values.redis.host }}"
            - name: SPRING_REDIS_PORT
              value: "{{ .Values.redis.port }}"
            - name: SPRING_REDIS_PASSWORD
              value: "{{ .Values.redis.password }}"
            - name: LIST_OF_PROFILE_ENDPOINTS
              value: "{{ .Values.chat.profileEndpoints}}"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: spring-chat-autoscaling
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.chat.releaseName }}-deployment
  minReplicas: {{ .Values.chat.hpa.minReplicas }}
  maxReplicas: {{ .Values.chat.hpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.chat.hpa.targetCPUUtilizationPercentage }}
  {{- end }}