 apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-profile-deployment
  labels:
    app: profile-service
spec:
  replicas: {{ .Values.profile.replicaCount }}
  selector:
    matchLabels:
      app: profile-service
  template:
    metadata:
      labels:
        app: profile-service
    spec:
      containers:
        - name: profile-service
          image: "{{ .Values.profile.image }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: {{ .Values.profile.hpa.cpuRequest }}
          env:
            - name: MYSQL_DB_HOST
              value: "{{ .Values.profile.mysql.host }}"
            - name: MYSQL_DB_PORT
              value: "{{ .Values.profile.mysql.port }}"
            - name: MYSQL_DB_USER
              valueFrom:
                secretKeyRef:
                  name: profile-secret
                  key: mysql-username
            - name: MYSQL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: profile-secret
                  key: mysql-password
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: spring-profile-autoscaling
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.profile.releaseName }}-deployment
  minReplicas: {{ .Values.profile.hpa.minReplicas }}
  maxReplicas: {{ .Values.profile.hpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.profile.hpa.targetCPUUtilizationPercentage }}
