apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.login.releaseName }}-deployment"
  labels:
    app: spring-login
spec:
  replicas: {{ .Values.login.replicaCount }}
  selector:
    matchLabels:
      app: spring-login
  template:
    metadata:
      labels:
        app: spring-login
    spec:
      containers:
        - name: spring-login
          image: "{{ .Values.login.image }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: {{ .Values.login.hpa.cpuRequest }}
          env:
            - name: MYSQL_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: spring-login-config
                  key: MYSQL_DB_HOST
            - name: MYSQL_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: spring-login-config
                  key: MYSQL_DB_PORT
            - name: MYSQL_DB_USER
              valueFrom:
                secretKeyRef:
                  name: login-secret
                  key: mysql-username
            - name: MYSQL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: login-secret
                  key: mysql-password
            - name: CHAT_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: spring-login-config
                  key: CHAT_ENDPOINT
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: spring-login-autoscaling
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.login.releaseName }}-deployment
  minReplicas: {{ .Values.login.hpa.minReplicas }}
  maxReplicas: {{ .Values.login.hpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.login.hpa.targetCPUUtilizationPercentage }}
