apiVersion: v1
kind: Secret
metadata:
  name: chat-secret
type: Opaque
data:
  # MySQL credentials for chat service in base64 format
  mysql-username: "TXlzcWxVc2VyR2FiZQ==" 
  mysql-password: "TXlzcWxQYXNzd29yZDEyMyE="
