apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.chat.releaseName }}-service"
spec:
  type: "{{ .Values.chat.service.type }}"
  selector:
    app: spring-chat
  ports:
    - protocol: TCP
      port: {{ .Values.chat.service.port }}
      targetPort: {{ .Values.chat.service.targetPort }}
